export default {
  topType: [
    { label: "NoHair", value: "NoHair" },
    { label: "Eyepatch", value: "Eyepatch" },
    { label: "Hat", value: "Hat" },
    { label: "Hijab", value: "Hijab" },
    { label: "Turban", value: "Turban" },
    { label: "WinterHat1", value: "WinterHat1" },
    { label: "WinterHat2", value: "WinterHat2" },
    { label: "WinterHat3", value: "WinterHat3" },
    { label: "WinterHat4", value: "WinterHat4" },
    { label: "LongHairBigHair", value: "LongHairBigHair" },
    { label: "LongHairBob", value: "LongHairBob" },
    { label: "LongHairBun", value: "LongHairBun" },
    { label: "LongHairCurly", value: "LongHairCurly" },
    { label: "LongHairCurvy", value: "LongHairCurvy" },
    { label: "LongHairDreads", value: "LongHairDreads" },
    { label: "LongHairFrida", value: "LongHairFrida" },
    { label: "LongHairFro", value: "LongHairFro" },
    { label: "LongHairFroBand", value: "LongHairFroBand" },
    { label: "LongHairNotTooLong", value: "LongHairNotTooLong" },
    { label: "LongHairShavedSides", value: "LongHairShavedSides" },
    { label: "LongHairMiaWallace", value: "LongHairMiaWallace" },
    { label: "LongHairStraight", value: "LongHairStraight" },
    { label: "LongHairStraight2", value: "LongHairStraight2" },
    { label: "LongHairStraightStrand", value: "LongHairStraightStrand" },
    { label: "ShortHairDreads01", value: "ShortHairDreads01" },
    { label: "ShortHairDreads02", value: "ShortHairDreads02" },
    { label: "ShortHairFrizzle", value: "ShortHairFrizzle" },
    { label: "ShortHairShaggyMullet", value: "ShortHairShaggyMullet" },
    { label: "ShortHairShortCurly", value: "ShortHairShortCurly" },
    { label: "ShortHairShortFlat", value: "ShortHairShortFlat" },
    { label: "ShortHairShortRound", value: "ShortHairShortRound" },
    { label: "ShortHairShortWaved", value: "ShortHairShortWaved" },
    { label: "ShortHairSides", value: "ShortHairSides" },
    { label: "ShortHairTheCaesar", value: "ShortHairTheCaesar" },
    {
      label: "ShortHairTheCaesarSidePart",
      value: "ShortHairTheCaesarSidePart",
    },
  ],
  accessoriesType: [
    { label: "Blank", value: "Blank" },
    { label: "Kurt", value: "Kurt" },
    { label: "Prescription01", value: "Prescription01" },
    { label: "Prescription02", value: "Prescription02" },
    { label: "Round", value: "Round" },
    { label: "Sunglasses", value: "Sunglasses" },
    { label: "Wayfarers", value: "Wayfarers" },
  ],
  hatColor: [
    { label: "Black", value: "Black" },
    { label: "Blue01", value: "Blue01" },
    { label: "Blue02", value: "Blue02" },
    { label: "Blue03", value: "Blue03" },
    { label: "Gray01", value: "Gray01" },
    { label: "Gray02", value: "Gray02" },
    { label: "Heather", value: "Heather" },
    { label: "PastelBlue", value: "PastelBlue" },
    { label: "PastelGreen", value: "PastelGreen" },
    { label: "PastelOrange", value: "PastelOrange" },
    { label: "PastelRed", value: "PastelRed" },
    { label: "PastelYellow", value: "PastelYellow" },
    { label: "Pink", value: "Pink" },
    { label: "Red", value: "Red" },
    { label: "White", value: "White" },
  ],
  facialHairType: [
    { label: "Blank", value: "Blank" },
    { label: "BeardMedium", value: "BeardMedium" },
    { label: "BeardLight", value: "BeardLight" },
    { label: "BeardMagestic", value: "BeardMagestic" },
    { label: "MoustacheFancy", value: "MoustacheFancy" },
    { label: "MoustacheMagnum", value: "MoustacheMagnum" },
  ],
  facialHairColor: [
    { label: "Auburn", value: "Auburn" },
    { label: "Black", value: "Black" },
    { label: "Blonde", value: "Blonde" },
    { label: "BlondeGolden", value: "BlondeGolden" },
    { label: "Brown", value: "Brown" },
    { label: "BrownDark", value: "BrownDark" },
    { label: "Platinum", value: "Platinum" },
    { label: "Red", value: "Red" },
  ],
  clotheType: [
    { label: "BlazerShirt", value: "BlazerShirt" },
    { label: "BlazerSweater", value: "BlazerSweater" },
    { label: "CollarSweater", value: "CollarSweater" },
    { label: "GraphicShirt", value: "GraphicShirt" },
    { label: "Hoodie", value: "Hoodie" },
    { label: "Overall", value: "Overall" },
    { label: "ShirtCrewNeck", value: "ShirtCrewNeck" },
    { label: "ShirtScoopNeck", value: "ShirtScoopNeck" },
    { label: "ShirtVNeck", value: "ShirtVNeck" },
  ],
  clotheColor: [
    { label: "Black", value: "Black" },
    { label: "Blue01", value: "Blue01" },
    { label: "Blue02", value: "Blue02" },
    { label: "Blue03", value: "Blue03" },
    { label: "Gray01", value: "Gray01" },
    { label: "Gray02", value: "Gray02" },
    { label: "Heather", value: "Heather" },
    { label: "PastelBlue", value: "PastelBlue" },
    { label: "PastelGreen", value: "PastelGreen" },
    { label: "PastelOrange", value: "PastelOrange" },
    { label: "PastelRed", value: "PastelRed" },
    { label: "PastelYellow", value: "PastelYellow" },
    { label: "Pink", value: "Pink" },
    { label: "Red", value: "Red" },
    { label: "White", value: "White" },
  ],
  graphicType: [
    { label: "Bat", value: "Bat" },
    { label: "Cumbia", value: "Cumbia" },
    { label: "Deer", value: "Deer" },
    { label: "Diamond", value: "Diamond" },
    { label: "Hola", value: "Hola" },
    { label: "Pizza", value: "Pizza" },
    { label: "Resist", value: "Resist" },
    { label: "Selena", value: "Selena" },
    { label: "Bear", value: "Bear" },
    { label: "SkullOutline", value: "SkullOutline" },
    { label: "Skull", value: "Skull" },
  ],
  eyeType: [
    { label: "Close", value: "Close" },
    { label: "Cry", value: "Cry" },
    { label: "Default", value: "Default" },
    { label: "Dizzy", value: "Dizzy" },
    { label: "EyeRoll", value: "EyeRoll" },
    { label: "Happy", value: "Happy" },
    { label: "Hearts", value: "Hearts" },
    { label: "Side", value: "Side" },
    { label: "Squint", value: "Squint" },
    { label: "Surprised", value: "Surprised" },
    { label: "Wink", value: "Wink" },
    { label: "WinkWacky", value: "WinkWacky" },
  ],
  eyebrowType: [
    { label: "Angry", value: "Angry" },
    { label: "AngryNatural", value: "AngryNatural" },
    { label: "Default", value: "Default" },
    { label: "DefaultNatural", value: "DefaultNatural" },
    { label: "FlatNatural", value: "FlatNatural" },
    { label: "RaisedExcited", value: "RaisedExcited" },
    { label: "RaisedExcitedNatural", value: "RaisedExcitedNatural" },
    { label: "SadConcerned", value: "SadConcerned" },
    { label: "SadConcernedNatural", value: "SadConcernedNatural" },
    { label: "UnibrowNatural", value: "UnibrowNatural" },
    { label: "UpDown", value: "UpDown" },
    { label: "UpDownNatural", value: "UpDownNatural" },
  ],
  mouthType: [
    { label: "Concerned", value: "Concerned" },
    { label: "Default", value: "Default" },
    { label: "Disbelief", value: "Disbelief" },
    { label: "Eating", value: "Eating" },
    { label: "Grimace", value: "Grimace" },
    { label: "Sad", value: "Sad" },
    { label: "ScreamOpen", value: "ScreamOpen" },
    { label: "Serious", value: "Serious" },
    { label: "Smile", value: "Smile" },
    { label: "Tongue", value: "Tongue" },
    { label: "Twinkle", value: "Twinkle" },
    { label: "Vomit", value: "Vomit" },
  ],
  skinColor: [
    { label: "Tanned", value: "Tanned" },
    { label: "Yellow", value: "Yellow" },
    { label: "Pale", value: "Pale" },
    { label: "Light", value: "Light" },
    { label: "Brown", value: "Brown" },
    { label: "DarkBrown", value: "DarkBrown" },
    { label: "Black", value: "Black" },
  ],
};
